[system]
# 実行間隔（秒）
interval = 10
# 発信トークン接頭語
token_prefix = mDNSProxy_
# HTTP待ち受けポート
port = 80
# TTL初期値（秒）
ttl = 120
# ノード識別ID（複数サーバで重複しない値となる）
# 初回起動時に自動生成されるため手動記入不要
node_id =

[network]
# 外部mDNSプロキシIPアドレスとポート（カンマ区切りで複数指定可能）
external_proxies = 192.168.1.10:80,192.168.2.10:8080

# Wi-Fi設定（Pico用）
wifi_ssid = your_wifi_ssid
wifi_password = your_wifi_password
