name: Release Package Creator

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Remove excluded folders and files
        run: |
          # フォルダの除外
          rm -rf specs
          rm -rf .github
          rm -rf .gear

          # ファイルの除外
          rm -f .gitattributes
          rm -f .gitignore
          rm -f README.md

      - name: Create Release Archive
        run: |
          # .gitフォルダは保持したまま、アーカイブ対象から除外
          zip -r mdns_proxy-${{ github.event.release.tag_name }}.zip . -x ".git/*"

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} mdns_proxy-${{ github.event.release.tag_name }}.zip --clobber
          
